# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install linter
        pip install -r requirements.txt
        # Build code and install package locally
        pip install --editable .
    - name: Lint with flake8
      run: |
        cd documentapi/
        # Allow for aliases
        shopt -s expand_aliases
        # The GitHub editor is 127 chars wide
        alias flake8="flake8 --count --max-complexity=10 --show-source --max-line-length=127"
        flake8 .
        # Lint the doc example
        cd ../docs
        flake8 cookbook-ex.py
    - name: Build documentation
      run: |
        cd docs/
        sphinx-build -b spelling . build -W
        sphinx-build -b html . htmldir -W
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1
    - name: Test cookbook example
      run: |
        # Wait for server to finish startup
        sleep 3
        cd docs/
        python3 cookbook-ex.py
    - name: Run unit tests
      run: |
        cd tests/
        python3 test.py
