# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Poetry
      run: |
        # Install poetry
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install developer dependencies and documentapi
      run: poetry install
    - name: Lint with flake8
      run: |
        # The GitHub editor is 127 chars wide
        poetry run flake8 --count --max-complexity=10 --show-source --max-line-length=127 documentapi/ docs/cookbook-ex.py tests/
    - name: Build documentation
      run: |
        cd docs/
        poetry run sphinx-build -b spelling . build -W
        poetry run sphinx-build -b html . htmldir -W
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1
    - name: Test cookbook example
      run: |
        # Wait for server to finish startup
        sleep 3
        cd docs/
        poetry run python3 cookbook-ex.py
    - name: Run unit tests
      run: |
        cd tests/
        poetry run python3 test.py
