# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          # "3.7",
          # "3.8",
          "3.9"
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install developer dependencies and documentapi
      run: poetry install
    - name: Lint with flake8
      # The GitHub editor is 127 chars wide
      run: poetry run flake8 --count --show-source
    - name: Build documentation
      run: poetry run sphinx-build -b spelling . build -W
      working-directory: docs/
    - name: Check spelling in docs
      run: poetry run sphinx-build -b html . htmldir -W
      working-directory: docs/
    - name: Set up Aerospike Database
      uses: reugn/github-action-aerospike@v1
    - name: Wait for database to start
      run: sleep 3
    - name: Test cookbook example
      run: poetry run python3 cookbook-ex.py
      working-directory: docs/
    - name: Run unit tests
      run: poetry run coverage run -m unittest tests/test.py
    - name: Run coverage test
      run: poetry run coverage report --fail-under=100 --include=documentapi/api.py
